name: github
description: "GitHub Mobile"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  catcher: ^0.8.0
  dio: ^5.4.0
  ffi: ^2.1.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  path: ^1.8.3
  path_provider: ^2.1.1
  pretty_dio_logger: ^1.3.1
  realm: ^1.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  import_sorter: ^4.6.0
  build_runner: ^2.4.7
  riverpod_lint: ^2.3.7
  riverpod_generator: ^2.3.9
  custom_lint: ^0.5.7
  json_serializable: ^6.7.1
  freezed: ^2.4.6

flutter:
  uses-material-design: true
  generate: true

import_sorter:
  comments: false
